package top.yumik.core.designsystem.color

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val light_primary = Color(0xFF005BC1)
private val light_onPrimary = Color(0xFFFFFFFF)
private val light_primaryContainer = Color(0xFFD8E2FF)
private val light_onPrimaryContainer = Color(0xFF001A41)
private val light_secondary = Color(0xFF575E71)
private val light_onSecondary = Color(0xFFFFFFFF)
private val light_secondaryContainer = Color(0xFFDBE2F9)
private val light_onSecondaryContainer = Color(0xFF141B2C)
private val light_tertiary = Color(0xFF4A58A9)
private val light_onTertiary = Color(0xFFFFFFFF)
private val light_tertiaryContainer = Color(0xFFDEE0FF)
private val light_onTertiaryContainer = Color(0xFF000E5D)
private val light_error = Color(0xFFBA1A1A)
private val light_errorContainer = Color(0xFFFFDAD6)
private val light_onError = Color(0xFFFFFFFF)
private val light_onErrorContainer = Color(0xFF410002)
private val light_background = Color(0xFFFEFBFF)
private val light_onBackground = Color(0xFF1B1B1F)
private val light_surface = Color(0xFFFEFBFF)
private val light_onSurface = Color(0xFF1B1B1F)
private val light_surfaceVariant = Color(0xFFE1E2EC)
private val light_onSurfaceVariant = Color(0xFF44474F)
private val light_outline = Color(0xFF74777F)
private val light_inverseOnSurface = Color(0xFFF2F0F4)
private val light_inverseSurface = Color(0xFF303033)
private val light_inversePrimary = Color(0xFFADC6FF)
private val light_shadow = Color(0xFF000000)
private val light_surfaceTint = Color(0xFF005BC1)
private val light_outlineVariant = Color(0xFFC4C6D0)
private val light_scrim = Color(0xFF000000)

private val dark_primary = Color(0xFFADC6FF)
private val dark_onPrimary = Color(0xFF002E69)
private val dark_primaryContainer = Color(0xFF004494)
private val dark_onPrimaryContainer = Color(0xFFD8E2FF)
private val dark_secondary = Color(0xFFBFC6DC)
private val dark_onSecondary = Color(0xFF293041)
private val dark_secondaryContainer = Color(0xFF3F4759)
private val dark_onSecondaryContainer = Color(0xFFDBE2F9)
private val dark_tertiary = Color(0xFFBBC3FF)
private val dark_onTertiary = Color(0xFF182778)
private val dark_tertiaryContainer = Color(0xFF323F90)
private val dark_onTertiaryContainer = Color(0xFFDEE0FF)
private val dark_error = Color(0xFFFFB4AB)
private val dark_errorContainer = Color(0xFF93000A)
private val dark_onError = Color(0xFF690005)
private val dark_onErrorContainer = Color(0xFFFFDAD6)
private val dark_background = Color(0xFF1B1B1F)
private val dark_onBackground = Color(0xFFE3E2E6)
private val dark_surface = Color(0xFF1B1B1F)
private val dark_onSurface = Color(0xFFE3E2E6)
private val dark_surfaceVariant = Color(0xFF44474F)
private val dark_onSurfaceVariant = Color(0xFFC4C6D0)
private val dark_outline = Color(0xFF8E9099)
private val dark_inverseOnSurface = Color(0xFF1B1B1F)
private val dark_inverseSurface = Color(0xFFE3E2E6)
private val dark_inversePrimary = Color(0xFF005BC1)
private val dark_shadow = Color(0xFF000000)
private val dark_surfaceTint = Color(0xFFADC6FF)
private val dark_outlineVariant = Color(0xFF44474F)
private val dark_scrim = Color(0xFF000000)

internal val BlueLightColors = lightColorScheme(
    primary = light_primary,
    onPrimary = light_onPrimary,
    primaryContainer = light_primaryContainer,
    onPrimaryContainer = light_onPrimaryContainer,
    secondary = light_secondary,
    onSecondary = light_onSecondary,
    secondaryContainer = light_secondaryContainer,
    onSecondaryContainer = light_onSecondaryContainer,
    tertiary = light_tertiary,
    onTertiary = light_onTertiary,
    tertiaryContainer = light_tertiaryContainer,
    onTertiaryContainer = light_onTertiaryContainer,
    error = light_error,
    errorContainer = light_errorContainer,
    onError = light_onError,
    onErrorContainer = light_onErrorContainer,
    background = light_background,
    onBackground = light_onBackground,
    surface = light_surface,
    onSurface = light_onSurface,
    surfaceVariant = light_surfaceVariant,
    onSurfaceVariant = light_onSurfaceVariant,
    outline = light_outline,
    inverseOnSurface = light_inverseOnSurface,
    inverseSurface = light_inverseSurface,
    inversePrimary = light_inversePrimary,
    surfaceTint = light_surfaceTint,
    outlineVariant = light_outlineVariant,
    scrim = light_scrim,
)

internal val BlueDarkColors = darkColorScheme(
    primary = dark_primary,
    onPrimary = dark_onPrimary,
    primaryContainer = dark_primaryContainer,
    onPrimaryContainer = dark_onPrimaryContainer,
    secondary = dark_secondary,
    onSecondary = dark_onSecondary,
    secondaryContainer = dark_secondaryContainer,
    onSecondaryContainer = dark_onSecondaryContainer,
    tertiary = dark_tertiary,
    onTertiary = dark_onTertiary,
    tertiaryContainer = dark_tertiaryContainer,
    onTertiaryContainer = dark_onTertiaryContainer,
    error = dark_error,
    errorContainer = dark_errorContainer,
    onError = dark_onError,
    onErrorContainer = dark_onErrorContainer,
    background = dark_background,
    onBackground = dark_onBackground,
    surface = dark_surface,
    onSurface = dark_onSurface,
    surfaceVariant = dark_surfaceVariant,
    onSurfaceVariant = dark_onSurfaceVariant,
    outline = dark_outline,
    inverseOnSurface = dark_inverseOnSurface,
    inverseSurface = dark_inverseSurface,
    inversePrimary = dark_inversePrimary,
    surfaceTint = dark_surfaceTint,
    outlineVariant = dark_outlineVariant,
    scrim = dark_scrim,
)