package top.yumik.core.designsystem.color

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val light_primary = Color(0xFF865300)
private val light_onPrimary = Color(0xFFFFFFFF)
private val light_primaryContainer = Color(0xFFFFDDB9)
private val light_onPrimaryContainer = Color(0xFF2B1700)
private val light_secondary = Color(0xFF715A41)
private val light_onSecondary = Color(0xFFFFFFFF)
private val light_secondaryContainer = Color(0xFFFDDDBD)
private val light_onSecondaryContainer = Color(0xFF281805)
private val light_tertiary = Color(0xFF54633D)
private val light_onTertiary = Color(0xFFFFFFFF)
private val light_tertiaryContainer = Color(0xFFD7E9B8)
private val light_onTertiaryContainer = Color(0xFF131F02)
private val light_error = Color(0xFFBA1A1A)
private val light_errorContainer = Color(0xFFFFDAD6)
private val light_onError = Color(0xFFFFFFFF)
private val light_onErrorContainer = Color(0xFF410002)
private val light_background = Color(0xFFFFFBFF)
private val light_onBackground = Color(0xFF1F1B16)
private val light_surface = Color(0xFFFFFBFF)
private val light_onSurface = Color(0xFF1F1B16)
private val light_surfaceVariant = Color(0xFFF1E0D0)
private val light_onSurfaceVariant = Color(0xFF504539)
private val light_outline = Color(0xFF827568)
private val light_inverseOnSurface = Color(0xFFF9EFE7)
private val light_inverseSurface = Color(0xFF352F2A)
private val light_inversePrimary = Color(0xFFFFB961)
private val light_shadow = Color(0xFF000000)
private val light_surfaceTint = Color(0xFF865300)
private val light_outlineVariant = Color(0xFFD4C4B5)
private val light_scrim = Color(0xFF000000)

private val dark_primary = Color(0xFFFFB961)
private val dark_onPrimary = Color(0xFF472A00)
private val dark_primaryContainer = Color(0xFF663E00)
private val dark_onPrimaryContainer = Color(0xFFFFDDB9)
private val dark_secondary = Color(0xFFDFC1A2)
private val dark_onSecondary = Color(0xFF3F2D17)
private val dark_secondaryContainer = Color(0xFF57432B)
private val dark_onSecondaryContainer = Color(0xFFFDDDBD)
private val dark_tertiary = Color(0xFFBCCD9E)
private val dark_onTertiary = Color(0xFF273513)
private val dark_tertiaryContainer = Color(0xFF3D4B27)
private val dark_onTertiaryContainer = Color(0xFFD7E9B8)
private val dark_error = Color(0xFFFFB4AB)
private val dark_errorContainer = Color(0xFF93000A)
private val dark_onError = Color(0xFF690005)
private val dark_onErrorContainer = Color(0xFFFFDAD6)
private val dark_background = Color(0xFF1F1B16)
private val dark_onBackground = Color(0xFFEBE1D9)
private val dark_surface = Color(0xFF1F1B16)
private val dark_onSurface = Color(0xFFEBE1D9)
private val dark_surfaceVariant = Color(0xFF504539)
private val dark_onSurfaceVariant = Color(0xFFD4C4B5)
private val dark_outline = Color(0xFF9C8E81)
private val dark_inverseOnSurface = Color(0xFF1F1B16)
private val dark_inverseSurface = Color(0xFFEBE1D9)
private val dark_inversePrimary = Color(0xFF865300)
private val dark_shadow = Color(0xFF000000)
private val dark_surfaceTint = Color(0xFFFFB961)
private val dark_outlineVariant = Color(0xFF504539)
private val dark_scrim = Color(0xFF000000)


internal val YellowLightColors = lightColorScheme(
    primary = light_primary,
    onPrimary = light_onPrimary,
    primaryContainer = light_primaryContainer,
    onPrimaryContainer = light_onPrimaryContainer,
    secondary = light_secondary,
    onSecondary = light_onSecondary,
    secondaryContainer = light_secondaryContainer,
    onSecondaryContainer = light_onSecondaryContainer,
    tertiary = light_tertiary,
    onTertiary = light_onTertiary,
    tertiaryContainer = light_tertiaryContainer,
    onTertiaryContainer = light_onTertiaryContainer,
    error = light_error,
    errorContainer = light_errorContainer,
    onError = light_onError,
    onErrorContainer = light_onErrorContainer,
    background = light_background,
    onBackground = light_onBackground,
    surface = light_surface,
    onSurface = light_onSurface,
    surfaceVariant = light_surfaceVariant,
    onSurfaceVariant = light_onSurfaceVariant,
    outline = light_outline,
    inverseOnSurface = light_inverseOnSurface,
    inverseSurface = light_inverseSurface,
    inversePrimary = light_inversePrimary,
    surfaceTint = light_surfaceTint,
    outlineVariant = light_outlineVariant,
    scrim = light_scrim,
)

internal val YellowDarkColors = darkColorScheme(
    primary = dark_primary,
    onPrimary = dark_onPrimary,
    primaryContainer = dark_primaryContainer,
    onPrimaryContainer = dark_onPrimaryContainer,
    secondary = dark_secondary,
    onSecondary = dark_onSecondary,
    secondaryContainer = dark_secondaryContainer,
    onSecondaryContainer = dark_onSecondaryContainer,
    tertiary = dark_tertiary,
    onTertiary = dark_onTertiary,
    tertiaryContainer = dark_tertiaryContainer,
    onTertiaryContainer = dark_onTertiaryContainer,
    error = dark_error,
    errorContainer = dark_errorContainer,
    onError = dark_onError,
    onErrorContainer = dark_onErrorContainer,
    background = dark_background,
    onBackground = dark_onBackground,
    surface = dark_surface,
    onSurface = dark_onSurface,
    surfaceVariant = dark_surfaceVariant,
    onSurfaceVariant = dark_onSurfaceVariant,
    outline = dark_outline,
    inverseOnSurface = dark_inverseOnSurface,
    inverseSurface = dark_inverseSurface,
    inversePrimary = dark_inversePrimary,
    surfaceTint = dark_surfaceTint,
    outlineVariant = dark_outlineVariant,
    scrim = dark_scrim,
)